package dev.hashnode.rubenscheedler.esbanking.core.service;

import dev.hashnode.rubenscheedler.esbanking.core.domain.command.commands.CreateAccountCommand;
import dev.hashnode.rubenscheedler.esbanking.core.domain.command.commands.DepositCashCommand;
import dev.hashnode.rubenscheedler.esbanking.core.domain.command.commands.WithdrawCashCommand;
import dev.hashnode.rubenscheedler.esbanking.core.domain.model.value.Money;
import dev.hashnode.rubenscheedler.esbanking.core.domain.query.AccountView;
import dev.hashnode.rubenscheedler.esbanking.core.domain.query.queries.ViewAccountQuery;
import dev.hashnode.rubenscheedler.esbanking.core.service.exception.AccountCouldNotBeCreatedException;
import dev.hashnode.rubenscheedler.esbanking.core.service.exception.AccountCouldNotBeViewedException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.springframework.stereotype.Service;

import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ExecutionException;

@RequiredArgsConstructor
@Slf4j
@Service
public class AccountService {
    private final CommandGateway commandGateway;
    private final QueryGateway queryGateway;

    /**
     * Creates an account with initial balance 0. The account id is generated by the system.
     * @return AccountView with the account id and initial balance
     * @throws AccountCouldNotBeCreatedException If the account could not be created
     */
    public AccountView createAccount() throws AccountCouldNotBeCreatedException {
        UUID accountId = UUID.randomUUID();
        long initialBalance = 0L;
        CreateAccountCommand command = CreateAccountCommand.builder()
                .initialBalance(Money.builder().amount(initialBalance).build())
                .accountId(accountId)
                .build();
        log.debug(String.format("Account created with id %s and initialBalance %d", accountId, initialBalance));

        commandGateway.sendAndWait(command);

        try {
            return queryGateway.query(ViewAccountQuery.builder().accountId(accountId).build(), AccountView.class).get();
        } catch (InterruptedException | ExecutionException e) {
            log.debug(String.format("While querying account %s an exception occurred", accountId), e);
            throw new AccountCouldNotBeCreatedException("Account could not be created", e);
        }
    }

    /**
     * Retrieves the accountview projection for the given account id, if it exists.
     */
    public Optional<AccountView> getAccount(UUID accountId) {
        try {
            return Optional.ofNullable(queryGateway.query(ViewAccountQuery.builder().accountId(accountId).build(), AccountView.class).get());
        } catch (ExecutionException | InterruptedException e) {
            throw new AccountCouldNotBeViewedException("An exception occured while querying the account with id " + accountId, e);
        }
    }

    /**
     * Performs a cash deposit for an account.
     * @param accountId Account to deposit on
     * @param money Money to deposit on the account
     */
    public void depositCash(UUID accountId, Money money) {
        commandGateway.sendAndWait(DepositCashCommand.builder()
                        .accountId(accountId)
                        .amount(money)
                .build());
    }

    /**
     * Performs a cash withdrawal for an account.
     * @param accountId Account to withdraw from
     * @param money Money to withdraw from the account
     */
    public void withdrawCash(UUID accountId, Money money) {
        commandGateway.sendAndWait(WithdrawCashCommand.builder()
                .accountId(accountId)
                .amount(money)
                .build());
    }
}
